# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-08 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='lightning',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
    ]
