# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-08 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180907_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talks',
            name='link',
        ),
    ]
