# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-08 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_talks_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='cicle',
            field=models.IntegerField(default=3, verbose_name='Cicle'),
            preserve_default=False,
        ),
    ]
