# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-08 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_talks_cicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Current'),
        ),
    ]
